default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sniks # замените на ваш логин PostgreSQL
  password: Flasher007 # замените на ваш пароль PostgreSQL
  host: localhost

development:
  <<: *default
  database: my_project_name_development

test:
  <<: *default
  database: my_project_name_test

production:
  <<: *default
  database: my_project_name_production
  username: my_project_name
  password: <%= ENV['MY_PROJECT_NAME_DATABASE_PASSWORD'] %>
